### ISSUE TITLE
Android RSocket

### ISSUE THREAD

**Issue by robertroeser** [mostroverkhov/rsocket-java-backport#1]
We're working on an RSocket Android version that uses jdk6 / rxjava2. It's basically done, and we're waiting on Ben to get a repo. Would you be interested in helping wth that instead of re-implementing RSocket in Kotlin?

**Comment by mostroverkhov** [comment]
This port is already in runnable state and serves its purpose - there is little rationale to dump it now to  build java6 instead of kotlin - it is officially supported on android, and kotlin code can be run with jre6-8. Currently I am focused on enhancements(resumption & `Spring` support is top priority),  some of those require changes to original `rsocket-java` - I maintain its [fork](https://github.com/mostroverkhov/rsocket-java) to make it possible.

**Comment by robertroeser** [comment]
Ok - can we move it into the official RSocket repository? If you have an android version it would be nice to only have one for people to use.

My question is should we release the java 6 back port we have or do you think the Kotlin one you have would work for people?

**Comment by mostroverkhov** [comment]
I would vote for kotlin - either this repo or convert your work. kotlin & rxjava themselves are big advantage for promoting - and RSocket will benefit from adoption by wider audience. Reactive approach on UI is hyped topic in general, kotlin is pushed by G and I think its important to leverage that to advance such a useful project, given it fits modern "agenda" so well. People won't blog about something targeting java6. 

Of course, I support moving this to official repo, would prefer to mark it as incubating though. It lacks channels support due to differences in rxjava/reactor processors and current okhttp transport can close under heavy (on mobile scale) load.  Anyways I am planning to work on this project until it stable/feature complete as I see It.

**Comment by robertroeser** [comment]
@mostroverkhov Hi - got a repo for Android. It's exciting to see interest in RSocket and I think Kotlin is a good idea too. Here's the link to the repo- go ahead and send a pull request to it, and I'll merge what you got. 

https://github.com/rsocket/rsocket-android

**Comment by mostroverkhov** [comment]
@robertroeser just did it - hopefully return to repo tomorrow, and open few issues to align both projects
